### ISSUE TITLE
[TASK] Estimación Módulos Ventas y Soporte

### ISSUE THREAD

**Issue by jalbarrac** [jalbarrac/squad_10_2022_1c#29]
link a la tabla de estimacion para historias:
https://docs.google.com/spreadsheets/d/1CZITDiRxpxurGtAe_BoAmi56yP63lomPaxE8NjX6D9Y/edit?usp=sharing

**Comment by nishman22** [comment]
link a la tabla de estimacion para historias:
https://docs.google.com/spreadsheets/d/1CZITDiRxpxurGtAe_BoAmi56yP63lomPaxE8NjX6D9Y/edit?usp=sharing
